#!/usr/bin/env node
// node >= 20
//
// Builds every esbuild-bundled Worker in the WORKERS manifest. Dual-output:
//   worker/<name>/worker.bundle.js   ← user copies this into the CF dashboard
//   public/<outName>                 ← vite ships to dist/, Modal fetch reads it
//
// Adding a new Worker:
//   1. drop the entry at worker/<new>/src/index.ts
//   2. add a row to WORKERS below
//   3. that's it — `npm run build` (which chains to build:workers) picks it up
//
// Why a manifest array instead of auto-discover: worker/proactive-push/ has
// src/index.ts + wrangler.toml too, but its worker.bundle.js is hand-written
// (not an esbuild artifact). A naive scan of worker/*/src/index.ts would
// silently overwrite it. The manifest is explicit about which workers go
// through this pipeline.

import { build } from 'esbuild';
import { existsSync, statSync, readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

// Each entry can override entry/outWorker/outPublic paths so we can bundle:
//   - per-worker dirs (worker/<name>/src/index.ts → worker/<name>/worker.bundle.js + public/<outName>)
//   - flat single-file workers (worker/<name>.ts → public/<name>.js only — no worker.bundle.js sibling)
const WORKERS = [
  { name: 'instant-push', outName: 'instant-worker.bundle.js' },
  // instant-push 的 Deno Deploy 入口: 同一份 worker, 换 Deno.serve 包装。
  // worker.deno.bundle.js 供整份贴进 dash.deno.com Playground;
  // public/ 副本让站点把它当静态文件发布, Playground 里一行
  // `import "https://<站点>/instant-worker.deno.bundle.js"` 即可加载运行。
  {
    name: 'instant-push-deno',
    entryPath: 'worker/instant-push/src/deno.ts',
    outWorker: 'worker/instant-push/worker.deno.bundle.js',
    outPublic: 'public/instant-worker.deno.bundle.js',
  },
  // sw-keep-alive 是 SullyOS 的 service worker, 唯一消费者是浏览器从 /public 静态读, 不需要
  // CF wrangler 单独部署 (没 worker.bundle.js sibling). 之前 bundle 是手工跑 esbuild, Round 2
  // 起接进 build:workers 一起做, 避免 worker/sw-keep-alive.ts 跟 public/sw-keep-alive.js 漂移.
  {
    name: 'sw-keep-alive',
    entryPath: 'worker/sw-keep-alive.ts',
    outPublic: 'public/sw-keep-alive.js',
    skipWorkerOut: true,
  },
  // post-office 是纯后端（跨用户漂流信），不被前端静态 fetch，所以只产 worker.bundle.js
  // 供粘进 CF 面板（选 ES Module 格式）或对照 wrangler deploy，不写 public/。
  {
    name: 'post-office',
    skipPublicOut: true,
  },
];

// amsg-instant 0.3.0+ uses only Web Crypto (globalThis.crypto.subtle); the
// bundle has zero Node crypto imports, so CF Workers / Vercel Edge / Netlify
// Edge run with no compatibility flags and no runtime polyfill.
const sharedOpts = {
  format: 'esm',
  target: 'es2022',
  platform: 'neutral',
  bundle: true,
  minify: false,
  conditions: ['worker', 'browser', 'import', 'default'],
};

console.log(`Building ${WORKERS.length} worker bundle(s)...`);

for (const w of WORKERS) {
  const entry = resolve(root, w.entryPath || `worker/${w.name}/src/index.ts`);
  if (!existsSync(entry)) {
    console.error(`ERROR: entry not found for "${w.name}": ${entry}`);
    process.exit(1);
  }

  const banner = { js: `/* generated by scripts/build-workers.mjs — do not edit by hand */` };
  const outputs = [];

  let outWorker = null;
  if (!w.skipWorkerOut) {
    outWorker = resolve(root, w.outWorker || `worker/${w.name}/worker.bundle.js`);
    outputs.push(outWorker);
  }
  let outPublic = null;
  if (!w.skipPublicOut) {
    outPublic = resolve(root, w.outPublic || `public/${w.outName}`);
    outputs.push(outPublic);
  }
  if (outputs.length === 0) {
    console.error(`ERROR: "${w.name}" skips both worker and public output — nothing to build`);
    process.exit(1);
  }

  for (const out of outputs) {
    await build({ ...sharedOpts, entryPoints: [entry], outfile: out, banner });
  }

  const sizeRef = outWorker || outPublic;
  const sizeKb = (statSync(sizeRef).size / 1024).toFixed(1);
  const dest = [
    outWorker && (w.outWorker || `worker/${w.name}/worker.bundle.js`),
    outPublic && (w.outPublic || `public/${w.outName}`),
  ].filter(Boolean).join(' + ');
  console.log(`✓ ${w.name.padEnd(16)} ${sizeKb} KB  → ${dest}`);
}

// instant-worker.version.txt — Deno loader 冷启动时拉这个文件决定 bundle 版本号
// (见 utils/instantPushClient.ts 的 buildDenoLoaderSnippet)。从
// utils/instantWorkerVersion.ts 提取, 与 /version 路由同源, 不会漂移。
const versionSrc = readFileSync(resolve(root, 'utils/instantWorkerVersion.ts'), 'utf8');
const versionMatch = versionSrc.match(/INSTANT_WORKER_VERSION\s*=\s*'([^']+)'/);
if (!versionMatch) {
  console.error('ERROR: cannot extract INSTANT_WORKER_VERSION from utils/instantWorkerVersion.ts');
  process.exit(1);
}
writeFileSync(resolve(root, 'public/instant-worker.version.txt'), `${versionMatch[1]}\n`);
console.log(`✓ instant-worker.version.txt → ${versionMatch[1]}`);
